name: elixphoenix

services:
  app:
    image: exilesprx/elixphoenix-app:${VERSION:-main}
    depends_on:
      database:
        condition: service_healthy
    networks:
      - elixphoenix
    environment:
      APP_PORT: ${APP_PORT:-4000}
      APP_IP: ${APP_IP:-0.0.0.0}
      APP_SECRET_BASE_KEY: ${APP_SECRET_BASE_KEY}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      POSTGRES_DB: ${POSTGRES_DB:-elixphoenix}
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_HOSTNAME: ${POSTGRES_HOSTNAME:-database}

  database:
    image: exilesprx/elixphoenix-database:${VERSION:-main}
    shm_size: 128mb
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-postgres} -d ${POSTGRES_DB:-elixphoenix}"]
      interval: 5s
      timeout: 30s
      retries: 5
      start_period: 3s
    volumes:
      - database:/var/lib/postgresql/data
    networks:
      - elixphoenix
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      POSTGRES_DB: ${POSTGRES_DB:-elixphoenix}
      POSTGRES_USER: ${POSTGRES_USER:-postgres}

volumes:
  database:

networks:
  elixphoenix:
