name: elixphoenix

services:
  app:
    image: exilesprx/elixphoenix-app:${VERSION:-main}
    depends_on:
      database:
        condition: service_healthy
    networks:
      - elixphoenix
    environment:
      PHX_PORT: ${APP_PORT:-4000}
      PHX_HOST: ${APP_HOST:-}
      SECRET_KEY_BASE: ${APP_SECRET_KEY_BASE}
      DATABASE_URL: postgresql://${POSTGRES_USER:-postgres}:${POSTGRES_PASSWORD:-postgres}@${POSTGRES_HOSTNAME:-database}/${POSTGRES_DB:-elixphoenix}

  database:
    image: exilesprx/elixphoenix-database:${VERSION:-main}
    shm_size: 128mb
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "pg_isready -U ${POSTGRES_USER:-postgres} -d ${POSTGRES_DB:-elixphoenix}",
        ]
      interval: 5s
      timeout: 30s
      retries: 5
      start_period: 3s
    volumes:
      - database:/var/lib/postgresql/data
    networks:
      - elixphoenix
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      POSTGRES_DB: ${POSTGRES_DB:-elixphoenix}
      POSTGRES_USER: ${POSTGRES_USER:-postgres}

volumes:
  database:

networks:
  elixphoenix:
