name: elixphoenix

services:
  app:
    build:
      context: .docker/elixir
      target: dev
    tty: true
    stdin_open: true
    volumes:
      - app:/usr/src/app
    ports:
      - "4000:4000"

  database:
    build:
      context: .docker/postgres
      target: dev
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-postgres} -d ${POSTGRES_DB:-elixphoenix_dev}"]
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      POSTGRES_DB: ${POSTGRES_DB:-elixphoenix_dev}
      POSTGRES_USER: ${POSTGRES_USER:-postgres}

volumes:
  app:
    driver: local
    driver_opts:
      type: none
      device: .
      o: bind
