name: elixphoenix

services:
  app:
    image: exilesprx/elixphoenix-app:${VERSION:-main}
    depends_on:
      database:
        condition: service_healthy
    networks:
      - elixphoenix

  database:
    image: exilesprx/elixphoenix-database:${VERSION:-main}
    shm_size: 128mb
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB"]
      interval: 5s
      timeout: 30s
      retries: 5
      start_period: 3s
    volumes:
      - database:/var/lib/postgresql/data
    networks:
      - elixphoenix
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}

volumes:
  database:

networks:
  elixphoenix:
