name: elixphoenix

services:
  app:
    image: exilesprx/elixphoenix-app:${VERSION:-main}
    depends_on:
      database:
        condition: service_healthy
    networks:
      - elixphoenix
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=elixphoenix"

  database:
    image: exilesprx/elixphoenix-database:${VERSION:-main}
    shm_size: 128mb
    volumes:
      - database:/var/lib/postgresql/data
    networks:
      - elixphoenix

  traefik:
    build:
      context: .docker/traefik
      target: base
    labels:
      - "traefik.enable=true"
    networks:
      - elixphoenix
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

volumes:
  database:

networks:
  elixphoenix:
