name: elixphoenix

services:
  app:
    build:
      context: .docker/elixir
      target: dev
    tty: true
    stdin_open: true
    volumes:
      - app:/usr/src/app
    ports:
      - "4000:${APP_PORT:-4000}"
    environment:
      PHX_IP: ${APP_IP:-0.0.0.0}
      SECRET_KEY_BASE: wXjssXvWNHQ0R8LQy1JJmMINf/bpYeI4gdSG40jk1dzSsO6vZcE2JMWQ68qdlgle
      DATABASE_HOST: database
      DATABASE_NAME: ${POSTGRES_DB:-elixphoenix}
      DATABASE_USER: ${POSTGRES_USER:-postgres}
      DATABASE_PASSWORD: ${POSTGRES_PASSWORD:-postgres}

  database:
    build:
      context: .docker/postgres
      target: dev

volumes:
  app:
    driver: local
    driver_opts:
      type: none
      device: .
      o: bind
