name: elixphoenix

services:
  app:
    build:
      context: .docker/elixir
      target: dev
    tty: true
    stdin_open: true
    volumes:
      - app:/usr/src/app
    ports:
      - "4000:${APP_PORT:-4000}"
    environment:
      APP_SECRET_BASE_KEY: wXjssXvWNHQ0R8LQy1JJmMINf/bpYeI4gdSG40jk1dzSsO6vZcE2JMWQ68qdlgle

  database:
    build:
      context: .docker/postgres
      target: dev

volumes:
  app:
    driver: local
    driver_opts:
      type: none
      device: .
      o: bind
